### ISSUE TITLE
Add option to log timestamp

### ISSUE THREAD

**Issue by lucdetellis** [npm/npmlog#33] opened 2016-05-05 19:35 UTC
It would be nice to have an option to include the date and/or time at the beginning of each log message.

For example:
![2016-05-05 3:26pm info http Server Started at 0.0.0.0:8080](http://i.imgur.com/nbIq7uB.png)

I did find a fork of npmlog that does this (https://github.com/necccc/npmlog-ts), but it looks outdated.

**Comment by rwaldron** [comment] 2016-05-10 22:02
Duplicate of https://github.com/npm/npmlog/pull/24

**Comment by Dids** [comment] 2017-11-08 11:08
Here's an easy workaround:

```js
var log = require('npmlog')
Object.defineProperty(log, 'heading', { get: () => { return new Date().toUTCString() } })
log.headingStyle = { bg: '', fg: 'white' }
```

**Comment by wraithgar** [comment] 2022-02-09 19:11
Now that this.heading is only referenced once, the workaround works.

**Closed by wraithgar** 2022-02-09 19:11 UTC
