### ISSUE TITLE
setting maxRecordSize to 0 does not result in a empty records array

### ISSUE THREAD

**Issue by satazor** [npm/npmlog#30] opened 2016-03-06 11:41 UTC
If `maxRecordSize` is set to a value where `Math.floor(maxRecordSize * 0.9) === 0` then the records array will grow indefinitely.

**Comment by helio-frota** [comment] 2016-12-12 17:15
hi, I can't reproduce this.
When I `maxRecordSize` to `0`, it will be the same number of log entries.
This means, this is correct, right ?

**Comment by satazor** [comment] 2016-12-12 17:49
https://github.com/npm/npmlog/blame/c027c276f6f7e6c8d808767b0d611555e3ef5f61/log.js#L206

It's doing a slice(-0) which doesn't do anything.

**Comment by helio-frota** [comment] 2016-12-12 18:09
yup, I'm understanding this like this:
_if maxRecordSize is 0, then do nothing, keep the array (record) growing._
( since we don't care about the max size)
Which seems correct.

But, maybe the docs are not clear and needs to be improved, because it tells nothing about the maxRecord to be zero. https://github.com/npm/npmlog#logmaxrecordsize
In this case ^ :+1:.

Or I did not get the point at all.

**Comment by wraithgar** [comment] 2022-02-09 19:15
Closing due to age. Feel free to submit a readme update if you feel this still need clarifying

**Closed by wraithgar** 2022-02-09 19:15 UTC
