### ISSUE TITLE
profiling express application breaks with npmlog v3.0.0

### ISSUE THREAD

**Issue by DivineGod** [npm/npmlog#40] opened 2016-06-07 06:40 UTC
I noticed today while trying to profile a nodejs app which uses express, that the update to v3 of npmlog breaks when running v8 profiling.

Using this [reduced test case](https://gist.github.com/DivineGod/fe3b96de6f4ae4f9e238b8f5aa27f403) the following steps will reproduce the error
1. `npm run v3` -> causes an error
2. `npm run v2` -> works as expected

I haven't drilled down into npmlog to determine exactly what is causing this to happen.

**Comment by DivineGod** [comment] 2016-06-07 08:40
Node versions tested and result:
```
v6.2.0 - Does not work
v5.9.1 - Does not work
v4.4.2 - Does not work
v0.12.7 - Does not work
v0.10.32 - Works
```

**Comment by iarna** [comment] 2016-06-08 21:00
Interesting…

**Comment by iarna** [comment] 2016-06-08 21:02
@othiym23's suspicion is that this is related to the `setBlocking` change.

**Comment by iarna** [comment] 2016-06-08 22:35
It was not!

It's caused by `gauge`'s use of `signal-exit`. I've talked with @bcoe and he's going to patch `signal-exit` to be compatible with the profiler.

I'll close this issue when that change lands.

**Closed** 2020-07-28 04:22 UTC
